### ISSUE TITLE
Research setting heroku app for all machines

### ISSUE THREAD

**Issue by JakeSeib** [Po-Ta-Toes/subidos-api#16]
Currently only Sam's machine is configured to point to the deployed version of our API. Running i.e. `heroku open` or `git push heroku master` on other machines will do nothing.

Should determine how to set up so that any team member can push to the deployed API.

**Comment by JakeSeib** [comment]
Seems that since the heroku site is deployed on a personal account, Kevin and I should be added as collaborators with our emails.

The two ways of doing so are:
1. From the subidos-api directory, run
`heroku access:add joe@example.com`
2. Select the app in the dashboard > Click the Access tab > Click the Add collaborator button > In the New collaborator window, type their email address > Click Save changes.

My email for heroku is the same as we've been using in our commit messages. Check with Kevin if the same is true for him.

See: https://devcenter.heroku.com/articles/collaborating

**Comment by srsexton94** [comment]
Ah before I saw your comment I found this (which seemed a lot like an "organization" in GitHub?  Says teams under 5 people are free so we should be good there)
https://devcenter.heroku.com/articles/heroku-teams

I'll read into the above as well!

**Comment by srsexton94** [comment]
I added you the "collaborating" way - seemed to go through on my end!  I'll do the same for Kevin when we confirm his email

**Comment by JakeSeib** [comment]
Worked for me! For Kevin: after getting added as a collaborator, go to subidos-api repo in the command line, checkout to master, and run the following:

`heroku git:remote -a mysterious-wave-25390`
